/**
 * `pnpm run build:kb`: compile `kb/*.md` into `_shared/kb.generated.ts`.
 *
 * The agent bundler has no `.md` loader and a deployed run has no repo checkout, so the copilot
 * reads its knowledge base from a generated TypeScript module. The output is committed;
 * `build-kb.test.ts` fails when it is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export interface KbSource {
  slug: string;
  title: string;
  body: string;
}

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const KB_DIR = path.join(ROOT, "kb");
export const KB_OUT = path.join(ROOT, "_shared", "kb.generated.ts");

/** Every page, sorted by slug. The title is the first `# ` heading, else the slug. */
export function readKb(dir = KB_DIR): KbSource[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const text = readFileSync(path.join(dir, f), "utf8").trim();
      const heading = /^#\s+(.+)$/m.exec(text);
      return {
        slug: f.replace(/\.md$/, ""),
        title: heading ? heading[1].trim() : f.replace(/\.md$/, ""),
        body: text,
      };
    });
}

const templateLiteral = (s: string) =>
  "`" +
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") +
  "`";

/** The module source, already in prettier's style so `prettier --check` passes without a rewrite. */
export function renderKb(pages: KbSource[]): string {
  const entries = pages
    .map(
      (p) =>
        `  {\n    slug: ${JSON.stringify(p.slug)},\n    title: ${JSON.stringify(p.title)},\n    body: ${templateLiteral(p.body)},\n  },\n`,
    )
    .join("");
  return `// Generated by scripts/build-kb.ts from kb/*.md. Do not edit; run \`pnpm run build:kb\`.

export interface KbPage {
  slug: string;
  title: string;
  body: string;
}

export const KB: readonly KbPage[] = [
${entries}];
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const pages = readKb();
  writeFileSync(KB_OUT, renderKb(pages));
  console.log(`wrote ${path.relative(ROOT, KB_OUT)} (${pages.length} pages)`);
}
