import { chromium } from "playwright";
const S = process.env.S, URL = process.env.URL;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(URL);
await page.locator(".rail-workflows").waitFor();
await page.getByTestId("project-select-r5s-tree/proj-c").click();
const node = page.locator("[data-testid^=agent-map-node-]").first();
await node.waitFor();
await node.click();
await page.waitForTimeout(1500);
await page.screenshot({ path: `${S}/shots-r5s/peek.png` });
console.log(await page.locator("[data-testid]").evaluateAll((els) => [...new Set(els.map((e) => e.getAttribute("data-testid")))].filter((t) => /map|card|chat|assist/.test(t))));
await browser.close();
