import { chromium } from "playwright";
const S = process.env.S, URL = process.env.URL;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on("pageerror", (e) => console.log("pageerror", e.message));
await page.goto(URL);
await page.locator(".rail-workflows").waitFor();
await page.getByTestId("project-select-r5s-tree/proj-c").click();
await page.waitForTimeout(8000);
await page.screenshot({ path: `${S}/shots-r5s/map-c.png` });
console.log(await page.locator("[data-testid^=agent-map-node-]").count(), "nodes");
console.log((await page.locator("body").innerText()).slice(0, 1500));
await browser.close();
