import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BookOpen,
  Brain,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  Cloud,
  CloudOff,
  Code,
  Copy,
  CornerDownRight,
  CornerLeftUp,
  ExternalLink,
  FlaskConical,
  Folder,
  GitBranch,
  FolderOpen,
  FolderPlus,
  Frame,
  Globe,
  Hammer,
  HelpCircle,
  History,
  ImageUp,
  Info,
  LayoutTemplate,
  List,
  ListChecks,
  Loader,
  LogOut,
  type LucideIcon,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  MoreHorizontal,
  MoreVertical,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Play,
  Plug,
  Plus,
  Radio,
  RefreshCw,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareTerminal,
  Sun,
  Tags,
  Trash2,
  TriangleAlert,
  Wand2,
  Workflow,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
  CloudUpload,
} from "lucide-react";
import type { JSX } from "react";

/**
 * A curated map, not a barrel import of the whole icon set — keeps the bundle
 * tree-shakeable. MacroDef.icon is still free-form config; unknown names
 * fall back to HelpCircle rather than failing to render.
 */
const ICONS: Record<string, LucideIcon> = {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BookOpen,
  Brain,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  Cloud,
  CloudOff,
  CloudUpload,
  Code,
  Copy,
  CornerDownRight,
  CornerLeftUp,
  ExternalLink,
  FlaskConical,
  Folder,
  GitBranch,
  FolderOpen,
  FolderPlus,
  Frame,
  Globe,
  Hammer,
  History,
  ImageUp,
  Info,
  LayoutTemplate,
  List,
  ListChecks,
  Loader,
  LogOut,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  /* OVERFLOW MENUS — the rule, because there wasn't one.
     Both glyphs were in use with no written convention: MoreHorizontal in the
     rail header and the canvas action bar, MoreVertical on the plan card. The
     split was accidental, but it matches the common platform convention, so it
     is now the rule rather than a coincidence:

       MoreHorizontal (…)  a menu belonging to a BAR or a SECTION HEADER — it
                           acts on the thing named beside it (rail settings,
                           "more actions for <step>").
       MoreVertical   (⋮)  a menu belonging to ONE ROW or CARD in a stack — it
                           acts on that row. Vertical because it stacks with the
                           row, and because a horizontal ellipsis at the end of a
                           row of text reads as truncation.

     Both current uses already conform. Pick by what the menu acts on, not by
     which looks better in the slot. */
  MoreHorizontal,
  MoreVertical,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Play,
  Plug,
  Plus,
  Radio,
  RefreshCw,
  Search,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareTerminal,
  Sun,
  Tags,
  Trash2,
  TriangleAlert,
  Wand2,
  Workflow,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
};

export function Icon({ name, size = 16 }: { name: string; size?: number }): JSX.Element {
  const Component = ICONS[name] ?? HelpCircle;
  return <Component size={size} strokeWidth={1.75} aria-hidden="true" />;
}
