// AUTO-GENERATED by packages/agent-core/scripts/gen-version-fallback.mjs.
// Do NOT edit by hand. Regenerated on every build (agent-core `prebuild`) and in
// the release `version-packages` step, so it always matches the workspace's
// @sapiom/agent + @sapiom/tools versions and the offline scaffold fallback can no
// longer drift.
export const VERSION_FALLBACK = {
  agent: "0.10.1",
  tools: "0.30.0",
} as const;
