/**
 * Generate `src/_generated/version.ts` from package.json — the build-time
 * version constant `analytics.ts` embeds in usage events. A constant survives
 * bundling (where no package.json exists on disk near the bundled module),
 * unlike the runtime package.json walk-up, which remains only as a fallback.
 *
 * The file is gitignored and regenerated by the `gen:version` script, which is
 * chained into `build`, `test`, `typecheck`, and `dev` so it can never go
 * stale relative to package.json (e.g. after a changesets version bump).
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(
  fs.readFileSync(path.join(packageRoot, "package.json"), "utf8"),
);
if (typeof version !== "string" || version.length === 0) {
  throw new Error("package.json has no version to generate from");
}

const outDir = path.join(packageRoot, "src", "_generated");
const outFile = path.join(outDir, "version.ts");
const content = `/**
 * GENERATED FILE — do not edit, not committed. Regenerated from package.json
 * by \`scripts/generate-version.mjs\` (wired into the build/test/typecheck
 * scripts as \`gen:version\`).
 */
export const VERSION = ${JSON.stringify(version)};
`;

fs.mkdirSync(outDir, { recursive: true });
// Write only on change so watch-mode compilers don't churn on every run.
let current;
try {
  current = fs.readFileSync(outFile, "utf8");
} catch {
  current = undefined;
}
if (current !== content) fs.writeFileSync(outFile, content);
