/**
 * Generates the per-session Claude Code `--settings` file and the tiny
 * hook-emitter script it points at.
 *
 * Nothing here touches the user's own `~/.claude` config — everything is
 * written under the harness's generated-config directory and passed to
 * `claude` via `--settings <path>` for the lifetime of one session.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

import { HARNESS_PATHS } from "../../shared/types.js";
import { expandHome } from "../paths.js";

/**
 * The Claude Code hook events the harness listens for.
 */
const HOOK_EVENTS = [
  "SessionStart",
  "UserPromptSubmit",
  "PreToolUse",
  "PostToolUse",
  "Stop",
  "SessionEnd",
] as const;

export type ClaudeHookEvent = (typeof HOOK_EVENTS)[number];

/**
 * The two Claude Code themes that paint with the terminal's own 16-color ANSI
 * palette (`ansi:<name>`) instead of hardcoded 256-color hex. Selecting one of
 * these is what makes the embedded xterm's palette (Terminal.tsx's
 * DARK_ANSI/LIGHT_ANSI) authoritative over Claude's accent colors — without it
 * Claude emits fixed 256-color indices the palette can't touch. `theme` is not
 * a documented settings.json key but is honoured by Claude Code (verified on
 * 2.1.220); an older/newer build that ignores it simply falls back to its
 * default 256-color rendering, so this degrades gracefully rather than failing.
 */
export type ClaudeAnsiTheme = "dark-ansi" | "light-ansi";

export interface GenerateClaudeSettingsOptions {
  /** The harness session this config is generated for. */
  harnessSessionId: string;
  /**
   * Root directory generated configs live under. Defaults to
   * `HARNESS_PATHS.generated` (`~/.sapiom/harness/generated`). Override in
   * tests to avoid touching the real home directory.
   */
  generatedRoot?: string;
  /**
   * ANSI theme to pin for this session so the app's terminal palette controls
   * Claude's colors. Match it to the app theme (dark app → `dark-ansi`) or
   * secondary/dim text loses contrast. Omitted → no `theme` key is written and
   * Claude keeps its default (256-color) rendering.
   */
  claudeTheme?: ClaudeAnsiTheme;
}

export interface GeneratedClaudeSettings {
  /** Absolute path to the generated settings.json (pass as `--settings`). */
  settingsPath: string;
  /** Absolute path to the generated emit.cjs hook script. */
  emitScriptPath: string;
}

/**
 * The hook-emitter script. Self-contained CommonJS, node builtins only — it
 * runs as a bare `node <path>` child process spawned by Claude Code itself,
 * so it can't rely on the harness package (or any node_modules) being
 * resolvable from wherever the user's project lives.
 *
 * Contract with the harness server: reads the hook's stdin JSON, wraps it
 * with the hook event name and this session's id, and POSTs it to
 * SAPIOM_HARNESS_INGEST_URL with a bearer token. A dead or slow harness
 * server must never slow down or break the user's agent, so every failure
 * mode here is swallowed and the process always exits 0 quickly.
 */
const EMIT_SCRIPT_SOURCE = `#!/usr/bin/env node
"use strict";

// Generated by @sapiom/harness — do not edit by hand, it is overwritten
// every time a new session starts.

const hookEvent = process.argv[2] || "unknown";

// Absolute ceiling: whatever else happens, exit quickly so we never hang
// the agent's hook pipeline. 3s (not 1s): on a cold Windows loopback the
// original 1s ceiling raced the fetch below and the SessionStart POST — the
// only signal that flips a session to "ready" — silently lost.
const hardStop = setTimeout(() => {
  try {
    process.exit(0);
  } catch {
    // ignore
  }
}, 3000);

// Best-effort breadcrumb when the POST fails: one line beside this script.
// Every failure here is swallowed by design (a broken debug log must never
// break the hook), and the file is capped so a long-dead harness can't grow
// it unboundedly. Without this there is zero evidence anywhere when the
// ready-signal chain dies — the exact hole the Windows prompt-drop hid in.
function logEmitFailure(message) {
  try {
    const fs = require("node:fs");
    const path = require("node:path");
    const debugPath = path.join(__dirname, "emit-debug.log");
    try {
      if (fs.statSync(debugPath).size > 65536) return;
    } catch {
      // No file yet — fine.
    }
    fs.appendFileSync(debugPath, new Date().toISOString() + " " + hookEvent + " " + message + "\\n");
  } catch {
    // ignore
  }
}

function readStdin() {
  return new Promise((resolve) => {
    if (process.stdin.isTTY) {
      resolve("");
      return;
    }
    let data = "";
    const giveUp = setTimeout(() => resolve(data), 500);
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => {
      clearTimeout(giveUp);
      resolve(data);
    });
    process.stdin.on("error", () => {
      clearTimeout(giveUp);
      resolve(data);
    });
  });
}

async function main() {
  let payload = {};
  try {
    const raw = await readStdin();
    if (raw) payload = JSON.parse(raw);
  } catch {
    // Malformed stdin — still report that the hook fired, with no payload.
  }

  const ingestUrl = process.env.SAPIOM_HARNESS_INGEST_URL;
  if (!ingestUrl) return;

  const body = JSON.stringify({
    hookEvent: hookEvent,
    receivedAt: new Date().toISOString(),
    harnessSessionId: process.env.SAPIOM_HARNESS_SESSION_ID || null,
    payload: payload,
  });

  // 2s, not 200ms: loopback is normally instant (and a dead port fails
  // instantly with ECONNREFUSED), but a cold first accept on Windows can
  // exceed 200ms — and a timed-out SessionStart means the session never
  // reaches "ready" and the held first prompt is dropped. The hard stop
  // above still bounds the whole process at 3s, far under the agent's own
  // hook budget.
  const controller = new AbortController();
  const abortTimer = setTimeout(() => controller.abort(), 2000);

  try {
    await fetch(ingestUrl, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + (process.env.SAPIOM_HARNESS_INGEST_TOKEN || ""),
      },
      body: body,
      signal: controller.signal,
    });
  } catch (err) {
    // Fire-and-forget: ingest being down/slow must never surface here.
    logEmitFailure("POST failed: " + (err && err.message ? err.message : String(err)));
  } finally {
    clearTimeout(abortTimer);
  }
}

main()
  .catch(() => {})
  .finally(() => {
    clearTimeout(hardStop);
    process.exit(0);
  });
`;

function settingsDirFor(root: string, harnessSessionId: string): string {
  return path.join(root, harnessSessionId);
}

/**
 * Why the hook command invokes a BARE `node`, on every platform — this is a
 * decision, not an omission:
 *
 * Claude Code runs `command` hooks through a shell: `/bin/sh -c` on POSIX,
 * and on Windows **Git Bash by default, falling back to PowerShell** (per its
 * hooks documentation) — never cmd.exe. `node` is the one spelling all of
 * them resolve, PROVIDED a matching flavor exists on PATH:
 *
 *  - Git Bash resolves extensionless names and `.exe` — never a `.cmd`. A
 *    machine whose only `node` was the desktop app's `node.cmd` shim ran ZERO
 *    hooks: the SessionStart POST (the only thing that flips a session to
 *    "ready") silently died and the held first prompt was dropped. The
 *    desktop host now ships an extensionless `#!/bin/sh` node shim beside the
 *    `.cmd` for exactly this (harness-desktop's runtime-shims, mirroring
 *    npm's own three-flavor layout).
 *  - PowerShell and cmd resolve `node.cmd`/`node.exe` via PATHEXT.
 *
 * An absolute `"C:\…\node.exe"` looks more robust but is a trap: PowerShell's
 * `-Command` form parses a leading quoted string as an EXPRESSION, not an
 * invocation (it needs `&`), so embedding one would break the documented
 * PowerShell fallback — while adding nothing Git Bash or cmd need.
 */
const HOOK_NODE = "node";

/**
 * Write the generated settings.json + emit.cjs for one harness session.
 * Returns the settings.json path — pass it as `claude --settings <path>`.
 */
export async function generateClaudeSettings(
  options: GenerateClaudeSettingsOptions,
): Promise<GeneratedClaudeSettings> {
  const { claudeTheme } = options;
  const root = expandHome(options.generatedRoot ?? HARNESS_PATHS.generated);
  const dir = settingsDirFor(root, options.harnessSessionId);
  await fs.mkdir(dir, { recursive: true });

  const emitScriptPath = path.join(dir, "emit.cjs");
  await fs.writeFile(emitScriptPath, EMIT_SCRIPT_SOURCE, { mode: 0o755 });

  const hooks: Record<string, unknown> = {};
  for (const event of HOOK_EVENTS) {
    hooks[event] = [
      {
        matcher: "",
        hooks: [
          {
            type: "command",
            // The script path is double-quoted because Claude Code runs a
            // `command` hook through a shell (`/bin/sh -c …`; `cmd.exe` on
            // Windows). An unquoted path under a home directory that contains a
            // space (`/Users/First Last/.sapiom/harness/generated/…/emit.cjs`)
            // word-splits, so `node` receives `/Users/First` and the hook dies
            // with "Cannot find module" — the SessionStart hook then never
            // POSTs and the session's agentSessionId is never established
            // (the exact "exited before establishing a session id" failure).
            // Double quotes group the path on both sh and cmd.exe and are
            // stripped before `node` sees the argument. This is the harness
            // CLAUDE.md's "paths contain spaces — never hand a shell an
            // unquoted path" rule. The event name is a fixed identifier from
            // HOOK_EVENTS, so it needs no quoting.
            command: `${HOOK_NODE} "${emitScriptPath}" ${event}`,
          },
        ],
      },
    ];
  }

  const settingsPath = path.join(dir, "settings.json");
  const settings = claudeTheme ? { theme: claudeTheme, hooks } : { hooks };
  await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf8");

  return { settingsPath, emitScriptPath };
}
