/**
 * Generates the per-session Claude Code `--settings` file and the tiny
 * hook-emitter script it points at.
 *
 * Nothing here touches the user's own `~/.claude` config — everything is
 * written under the harness's generated-config directory and passed to
 * `claude` via `--settings <path>` for the lifetime of one session.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

import { HARNESS_PATHS } from "../../shared/types.js";
import { expandHome } from "../paths.js";

/**
 * The Claude Code hook events the harness listens for.
 * `Notification` fires when Claude Code needs user attention (e.g. a tool
 * permission prompt in auto mode) — used to show the chat attention banner.
 */
const HOOK_EVENTS = [
  "SessionStart",
  "UserPromptSubmit",
  "PreToolUse",
  "PostToolUse",
  "Stop",
  "SessionEnd",
  "Notification",
] as const;

export type ClaudeHookEvent = (typeof HOOK_EVENTS)[number];

export interface GenerateClaudeSettingsOptions {
  /** The harness session this config is generated for. */
  harnessSessionId: string;
  /**
   * Root directory generated configs live under. Defaults to
   * `HARNESS_PATHS.generated` (`~/.sapiom/harness/generated`). Override in
   * tests to avoid touching the real home directory.
   */
  generatedRoot?: string;
}

export interface GeneratedClaudeSettings {
  /** Absolute path to the generated settings.json (pass as `--settings`). */
  settingsPath: string;
  /** Absolute path to the generated emit.cjs hook script. */
  emitScriptPath: string;
}

/**
 * The hook-emitter script. Self-contained CommonJS, node builtins only — it
 * runs as a bare `node <path>` child process spawned by Claude Code itself,
 * so it can't rely on the harness package (or any node_modules) being
 * resolvable from wherever the user's project lives.
 *
 * Contract with the harness server: reads the hook's stdin JSON, wraps it
 * with the hook event name and this session's id, and POSTs it to
 * SAPIOM_HARNESS_INGEST_URL with a bearer token. A dead or slow harness
 * server must never slow down or break the user's agent, so every failure
 * mode here is swallowed and the process always exits 0 quickly.
 */
const EMIT_SCRIPT_SOURCE = `#!/usr/bin/env node
"use strict";

// Generated by @sapiom/harness — do not edit by hand, it is overwritten
// every time a new session starts.

const hookEvent = process.argv[2] || "unknown";

// Absolute ceiling: whatever else happens, exit quickly so we never hang
// the agent's hook pipeline.
const hardStop = setTimeout(() => {
  try {
    process.exit(0);
  } catch {
    // ignore
  }
}, 1000);

function readStdin() {
  return new Promise((resolve) => {
    if (process.stdin.isTTY) {
      resolve("");
      return;
    }
    let data = "";
    const giveUp = setTimeout(() => resolve(data), 300);
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => {
      data += chunk;
    });
    process.stdin.on("end", () => {
      clearTimeout(giveUp);
      resolve(data);
    });
    process.stdin.on("error", () => {
      clearTimeout(giveUp);
      resolve(data);
    });
  });
}

async function main() {
  let payload = {};
  try {
    const raw = await readStdin();
    if (raw) payload = JSON.parse(raw);
  } catch {
    // Malformed stdin — still report that the hook fired, with no payload.
  }

  const ingestUrl = process.env.SAPIOM_HARNESS_INGEST_URL;
  if (!ingestUrl) return;

  const body = JSON.stringify({
    hookEvent: hookEvent,
    receivedAt: new Date().toISOString(),
    harnessSessionId: process.env.SAPIOM_HARNESS_SESSION_ID || null,
    payload: payload,
  });

  const controller = new AbortController();
  const abortTimer = setTimeout(() => controller.abort(), 200);

  try {
    await fetch(ingestUrl, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: "Bearer " + (process.env.SAPIOM_HARNESS_INGEST_TOKEN || ""),
      },
      body: body,
      signal: controller.signal,
    });
  } catch {
    // Fire-and-forget: ingest being down/slow must never surface here.
  } finally {
    clearTimeout(abortTimer);
  }
}

main()
  .catch(() => {})
  .finally(() => {
    clearTimeout(hardStop);
    process.exit(0);
  });
`;

function settingsDirFor(root: string, harnessSessionId: string): string {
  return path.join(root, harnessSessionId);
}

/**
 * Write the generated settings.json + emit.cjs for one harness session.
 * Returns the settings.json path — pass it as `claude --settings <path>`.
 */
export async function generateClaudeSettings(
  options: GenerateClaudeSettingsOptions,
): Promise<GeneratedClaudeSettings> {
  const root = expandHome(options.generatedRoot ?? HARNESS_PATHS.generated);
  const dir = settingsDirFor(root, options.harnessSessionId);
  await fs.mkdir(dir, { recursive: true });

  const emitScriptPath = path.join(dir, "emit.cjs");
  await fs.writeFile(emitScriptPath, EMIT_SCRIPT_SOURCE, { mode: 0o755 });

  const hooks: Record<string, unknown> = {};
  for (const event of HOOK_EVENTS) {
    hooks[event] = [
      {
        matcher: "",
        hooks: [
          {
            type: "command",
            command: `node ${emitScriptPath} ${event}`,
          },
        ],
      },
    ];
  }

  const settingsPath = path.join(dir, "settings.json");
  await fs.writeFile(settingsPath, JSON.stringify({ hooks }, null, 2) + "\n", "utf8");

  return { settingsPath, emitScriptPath };
}
