/**
 * Shared types for LangChain integration
 */
import type { SapiomClient } from '../../../lib/SapiomClient';
import type { BaseSapiomIntegrationConfig } from '../../shared';

/**
 * Configuration for Sapiom model tracking
 */
export interface SapiomModelConfig extends BaseSapiomIntegrationConfig {
  /**
   * Workflow trace identifier
   *
   * Purpose:
   * - Groups related transactions (LLM calls + tool calls) under one trace
   * - Enables workflow cost tracking and duration analysis
   * - Allows correlation with your distributed tracing system
   *
   * Behavior:
   * - Provided: Uses your ID (e.g., "checkout-123", "user-456-conv")
   * - Not provided: SDK auto-generates UUID with "sdk-" prefix
   * - Reusable: Access via model.currentTraceId after invoke
   *
   * Per-invoke override:
   * - Pass different ID in options.metadata.__sapiomTraceId
   * - Temporarily uses override, then returns to default
   *
   * Backend behavior:
   * - First use: Creates trace with this ID
   * - Subsequent: Finds existing trace by this ID
   * - Race-safe: Concurrent calls with same ID share one trace
   *
   * @example
   * ```typescript
   * // User-provided
   * const model = new SapiomChatOpenAI({ model: "gpt-4" }, {
   *   traceId: "checkout-session-abc"
   * });
   *
   * // Auto-generated
   * const model = new SapiomChatOpenAI({ model: "gpt-4" });
   * console.log(model.currentTraceId);  // "sdk-a1b2c3d4-..."
   * ```
   */
  traceId?: string;

  /**
   * Agent identifier (UUID or numeric ID like AG-001)
   *
   * Purpose:
   * - Tags transactions with a specific agent for filtering and analytics
   * - Enables agent-level cost tracking and usage analysis
   *
   * Behavior:
   * - Provided: Uses existing agent with this ID
   * - Agent must be ACTIVE to be used
   * - Cannot be used with agentName
   *
   * @example
   * ```typescript
   * const model = new SapiomChatOpenAI({ model: "gpt-4" }, {
   *   agentId: "AG-001"  // or UUID
   * });
   * ```
   */
  agentId?: string;

  /**
   * Agent name for find-or-create behavior
   *
   * Purpose:
   * - Automatically creates agent if it doesn't exist
   * - Convenient for dynamic agent creation
   * - Ensures consistent agent tagging across runs
   *
   * Behavior:
   * - Provided: Finds existing agent by name or creates new ACTIVE agent
   * - Cannot be used with agentId
   * - Agents are tenant-scoped (unique per organization)
   *
   * @example
   * ```typescript
   * const model = new SapiomChatOpenAI({ model: "gpt-4" }, {
   *   agentName: "customer-support-bot"
   * });
   * ```
   */
  agentName?: string;

  /**
   * Service name for transactions
   * If not provided, inferred from model class name
   * Examples: "openai", "anthropic", "google"
   */
  serviceName?: string;

  /**
   * Whether to track and authorize LLM calls
   * @default true
   */
  enabled?: boolean;

  /**
   * Callbacks for LLM operations
   */
  onBeforeGenerate?: (txId: string, estimatedTokens: number, traceId: string | undefined) => void;
  onAfterGenerate?: (txId: string, actualTokens: number, cost: number) => void;
  onAuthorizationDenied?: (txId: string, reason: string) => void;
}

/**
 * Configuration for Sapiom tool tracking
 */
export interface SapiomToolConfig extends BaseSapiomIntegrationConfig {
  /**
   * Service name for transactions
   * If not provided, defaults to "tool" or inferred from tool metadata
   */
  serviceName?: string;

  /**
   * Action for transactions
   * @default "call"
   */
  actionName?: string;

  /**
   * Resource for transactions
   * If not provided, defaults to tool.name
   */
  resourceName?: string;

  /**
   * Additional qualifiers for transactions
   */
  qualifiers?: Record<string, any>;

  /**
   * Whether to require pre-authorization
   * @default true
   */
  requireAuthorization?: boolean;

  /**
   * Authorization callbacks
   */
  onBeforeCall?: (txId: string, toolName: string, args: any, traceId: string | undefined) => void;
  onAfterCall?: (txId: string, result: any) => void;
  onAuthorizationDenied?: (txId: string, reason: string) => void;

  /**
   * Payment callbacks (for MCP tools that return 402 errors)
   */
  onPaymentRequired?: (txId: string, payment: any, toolName: string) => void;
  onPaymentAuthorized?: (txId: string) => void;
}

/**
 * Trace metadata injected into RunnableConfig
 * Used internally to propagate trace context through LangChain execution
 *
 * @internal
 */
export interface SapiomSessionMetadata {
  /**
   * Current trace ID for this execution context
   *
   * This is the user's workflow identifier that groups related transactions.
   * It can be:
   * - User-provided from config.traceId
   * - Auto-generated by SDK (prefixed with "sdk-")
   * - Overridden per-invoke via options.metadata.__sapiomTraceId
   *
   * Internally, this maps to backend's trace.externalId field.
   */
  __sapiomTraceId: string;

  /**
   * Agent ID for tagging transactions
   *
   * When set, all transactions in this context will be tagged with this agent.
   * Can be:
   * - User-provided from config.agentId (UUID or numeric ID like AG-001)
   * - Overridden per-invoke via options.metadata.__sapiomAgentId
   */
  __sapiomAgentId?: string;

  /**
   * Agent name for find-or-create behavior
   *
   * When set, transactions will use or create an agent with this name.
   * Can be:
   * - User-provided from config.agentName
   * - Overridden per-invoke via options.metadata.__sapiomAgentName
   */
  __sapiomAgentName?: string;

  /**
   * Shared SapiomClient instance
   * All wrappers use this for consistency
   */
  __sapiomClient?: SapiomClient;

  /**
   * Shared TransactionAuthorizer instance (when using agents)
   * Avoids creating new authorizer on every tool call
   * @internal
   */
  __sapiomAuthorizer?: any;  // Avoid circular import with TransactionAuthorizer

  /**
   * Agent invocation transaction ID (when using agents)
   * Root transaction for this trace
   */
  __sapiomAgentTxId?: string;

  /**
   * Agent invoke transaction (when invoke calls stream internally)
   * Used to prevent duplicate transactions
   * @internal
   */
  __sapiomAgentInvokeTransaction?: any;
}

/**
 * Marker interface for Sapiom-wrapped objects
 *
 * @internal
 */
export interface SapiomWrapped {
  __sapiomClient: SapiomClient;
  __sapiomWrapped: true;
}
