// Generated by scripts/build-kb.ts from kb/*.md. Do not edit; run `pnpm run build:kb`.

export interface KbPage {
  slug: string;
  title: string;
  body: string;
}

export const KB: readonly KbPage[] = [
  {
    slug: "account-access",
    title: "Account access",
    body: `# Account access

- **Password reset:** use "Forgot password" on the sign-in page. The link is valid for 1 hour.
  Workspaces with SSO enforced cannot reset a Relaybox password; sign in through the identity
  provider instead.
- **Locked out:** 10 failed sign-ins lock the account for 30 minutes.
- **Two-factor authentication:** owners can require it for everyone under **Settings → Security**.
  A user who lost their device can use a recovery code; otherwise a workspace owner can reset
  their 2FA from the member list.
- **Roles:** Owner (billing, security, delete workspace), Admin (members, integrations, exports),
  Member. Only an owner can promote someone to owner.
- **Removing a member** signs them out everywhere and revokes their API tokens immediately.
- **Owner left the company:** support can transfer ownership after verifying a request from
  another admin's verified email.`,
  },
  {
    slug: "billing",
    title: "Billing and plans",
    body: `# Billing and plans

Plans: Free (3 seats), Team (per seat, monthly or annual) and Business (per seat, annual,
adds SSO, audit log and scheduled exports).

- Invoices are issued on the billing date and emailed to the billing contact. Past invoices are
  under **Settings → Billing → Invoices**.
- Adding a seat is prorated for the rest of the period. Removing a seat takes effect at the next
  renewal; there are no partial refunds.
- If a card payment fails, Relaybox retries for 14 days and emails the billing contact. The
  workspace stays fully usable during that time, then drops to read-only until paid.
- Changing the billing contact, VAT id or address: **Settings → Billing → Details**. Only
  workspace owners can change billing.
- Refunds for a duplicate or mistaken charge are handled by support; reply with the invoice
  number.`,
  },
  {
    slug: "exports",
    title: "Data exports",
    body: `# Data exports

Workspace admins can export data from **Settings → Data → Export**.

- Formats: CSV (one file per table, zipped) and JSON Lines.
- Exports run in the background. Small workspaces finish in minutes; very large ones can take a
  few hours. The admin who started the export gets an email with a download link.
- Download links expire after 7 days. Start a new export to get a fresh link.
- Only one export per workspace runs at a time; a second request waits for the first.
- Timestamps are UTC in ISO 8601. Deleted records are not included.
- Scheduled exports (daily or weekly, to an S3 bucket) are available on the Business plan.`,
  },
  {
    slug: "webhooks",
    title: "Webhooks",
    body: `# Webhooks

Relaybox sends a webhook for every event a workspace subscribes to under
**Settings → Webhooks**. Each delivery is an HTTPS \`POST\` with a JSON body and an
\`X-Relaybox-Signature\` header (HMAC-SHA256 of the raw body with the endpoint's signing secret).

- Your endpoint must answer \`2xx\` within 10 seconds. Anything else counts as a failure.
- Failed deliveries retry 8 times with exponential backoff over about 24 hours.
- After 50 consecutive failures the endpoint is paused and the workspace owner gets an email.
  Fix the endpoint, then click **Resume** on the endpoint page; paused events are replayed.
- **Redeliver** on any event in the delivery log sends it again immediately.
- A signature mismatch is almost always a body that was parsed and re-serialized before
  verification. Verify against the raw bytes.
- Rotating the signing secret keeps the old secret valid for 24 hours.`,
  },
];
