import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const SCRIPT = fileURLToPath(
  new URL("./mcp-instructions-snapshot.mjs", import.meta.url),
);

const BODY = "# Primer\n\nUse `defineAgent`; never ${interpolate} by hand.";
const DIGEST = createHash("sha256").update(BODY, "utf8").digest("hex");
const FOOTER = `_Sapiom teaching content · authoring · release 9.9 · ${DIGEST.slice(0, 12)} · served live._`;

/** A backend stand-in serving `body` with exactly the given stamp headers. */
async function serve(body, headers) {
  const server = createServer((req, res) => {
    assert.equal(req.url, "/v1/mcp/instructions");
    res.writeHead(200, {
      "content-type": "text/markdown; charset=utf-8",
      ...headers,
    });
    res.end(body);
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  return {
    url: `http://127.0.0.1:${server.address().port}`,
    close: () => new Promise((resolve) => server.close(resolve)),
  };
}

/**
 * Run the generator as a child process. Async on purpose: the backend stand-in
 * lives in this process, so a synchronous spawn would block the event loop and
 * the child's fetch would never be answered.
 */
function run(apiURL, outputPath) {
  return new Promise((resolve) => {
    execFile(
      process.execPath,
      [SCRIPT, "--api-url", apiURL, "--out", outputPath],
      { encoding: "utf8" },
      (error, stdout, stderr) => {
        resolve({ status: error ? error.code : 0, stdout, stderr });
      },
    );
  });
}

test("refuses a body served without X-Sapiom-Content-Digest", async (t) => {
  const dir = await mkdtemp(join(tmpdir(), "mcp-snapshot-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const backend = await serve(`${BODY}\n\n${FOOTER}`, {
    "x-sapiom-content-release": "9.9",
  });
  t.after(backend.close);

  const out = join(dir, "instructions.generated.ts");
  const result = await run(backend.url, out);

  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /carried no X-Sapiom-Content-Digest header; refusing to snapshot an unstamped body/,
  );
  await assert.rejects(readFile(out), { code: "ENOENT" });
});

test("refuses a body served without X-Sapiom-Content-Release", async (t) => {
  const dir = await mkdtemp(join(tmpdir(), "mcp-snapshot-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const backend = await serve(`${BODY}\n\n${FOOTER}`, {
    "x-sapiom-content-digest": DIGEST.slice(0, 12),
  });
  t.after(backend.close);

  const result = await run(backend.url, join(dir, "instructions.generated.ts"));

  assert.equal(result.status, 1);
  assert.match(result.stderr, /carried no X-Sapiom-Content-Release header/);
});

test("refuses a body whose sha-256 does not match the served digest", async (t) => {
  const dir = await mkdtemp(join(tmpdir(), "mcp-snapshot-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const backend = await serve(`${BODY}\n\n${FOOTER}`, {
    "x-sapiom-content-release": "9.9",
    "x-sapiom-content-digest": "0123456789ab",
  });
  t.after(backend.close);

  const out = join(dir, "instructions.generated.ts");
  const result = await run(backend.url, out);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /digest mismatch/);
  await assert.rejects(readFile(out), { code: "ENOENT" });
});

test("writes a stamped body without its footer, then is a no-op on the second run", async (t) => {
  const dir = await mkdtemp(join(tmpdir(), "mcp-snapshot-"));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const backend = await serve(`${BODY}\n\n${FOOTER}\n`, {
    "x-sapiom-content-release": "9.9",
    "x-sapiom-content-digest": DIGEST.slice(0, 12),
    "x-sapiom-content-key": "authoring",
  });
  t.after(backend.close);

  const out = join(dir, "instructions.generated.ts");
  const first = await run(backend.url, out);
  assert.equal(first.status, 0, first.stderr);
  assert.match(
    first.stdout,
    /^wrote .*release 9\.9, digest .{12} \(matches X-Sapiom-Content-Digest\)/,
  );

  const generated = await readFile(out, "utf8");
  assert.match(
    generated,
    /^\/\/ GENERATED by scripts\/mcp-instructions-snapshot\.mjs — do not edit\./,
  );
  assert.match(generated, /AUTHORING_INSTRUCTIONS_RELEASE = "9\.9"/);
  assert.match(
    generated,
    new RegExp(`AUTHORING_INSTRUCTIONS_DIGEST =\\s*"${DIGEST}"`),
  );
  assert.doesNotMatch(generated, /Sapiom teaching content/);
  // The body round-trips through the template literal: escaped `${` and backticks.
  assert.match(generated, /never \\\$\{interpolate\} by hand\./);
  const { AUTHORING_INSTRUCTIONS } = await import(
    `data:text/javascript,${encodeURIComponent(generated.replace(/^\/\/.*$/gm, "").replace(/\/\*\*[\s\S]*?\*\//g, ""))}`
  );
  assert.equal(AUTHORING_INSTRUCTIONS, BODY);

  const second = await run(backend.url, out);
  assert.equal(second.status, 0, second.stderr);
  assert.match(second.stdout, /already matches/);
  assert.equal(await readFile(out, "utf8"), generated);
});
